from __future__ import annotations

import argparse
import os
import subprocess
from pathlib import Path

from .common import echo, ensure_dir, open_url, output, powershell, run
from .config import DEFAULT_COMFYUI_HOME, DEFAULT_COMFYUI_MODEL_ROOT, DEFAULT_COMFYUI_PORT


REPO_URL = "https://github.com/Comfy-Org/ComfyUI.git"
REPO_ROOT = Path(__file__).resolve().parents[2]
PROMPT_LOGGER_SOURCE = (
    REPO_ROOT / "src" / "comfyui" / "custom_nodes" / "win_models_prompt_logger.py"
)
DEFAULT_TORCH_INDEX = os.environ.get(
    "COMFYUI_TORCH_INDEX_URL", "https://download.pytorch.org/whl/cu130"
)
MODEL_SUBDIRS = (
    "checkpoints",
    "clip",
    "clip_vision",
    "configs",
    "controlnet",
    "diffusion_models",
    "embeddings",
    "loras",
    "style_models",
    "text_encoders",
    "unet",
    "upscale_models",
    "vae",
)


def venv_python(comfy_home: Path) -> Path:
    python = comfy_home / ".venv" / "Scripts" / "python.exe"
    if not python.exists():
        raise FileNotFoundError(
            f"Missing ComfyUI venv at {python}. Run: just comfy setup"
        )
    return python


def ensure_comfy_repo(comfy_home: Path, *, update: bool = False) -> None:
    if (comfy_home / ".git").exists():
        if update:
            run(["git", "-C", comfy_home, "pull", "--ff-only"])
        else:
            echo(f"ComfyUI repo already present: {comfy_home}")
        return

    if comfy_home.exists() and any(comfy_home.iterdir()):
        raise FileExistsError(
            f"{comfy_home} exists but is not a git checkout. Move it aside or set COMFYUI_HOME."
        )

    ensure_dir(comfy_home.parent)
    run(["git", "clone", REPO_URL, comfy_home])


def write_extra_model_paths(comfy_home: Path, model_root: Path) -> Path:
    ensure_dir(model_root)
    for subdir in MODEL_SUBDIRS:
        ensure_dir(model_root / subdir)

    config = comfy_home / "extra_model_paths.yaml"
    lines = [
        "# Generated by win-models. Keep shared diffusion assets under COMFYUI_MODEL_ROOT.",
        "win_models:",
        f"    base_path: {model_root}",
        "    is_default: true",
    ]
    for subdir in MODEL_SUBDIRS:
        lines.append(f"    {subdir}: {subdir}")
    config.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    echo(f"Wrote {config}")
    return config


def install_prompt_logger_node(comfy_home: Path) -> Path:
    if not PROMPT_LOGGER_SOURCE.exists():
        raise FileNotFoundError(f"Missing prompt logger source: {PROMPT_LOGGER_SOURCE}")
    target = comfy_home / "custom_nodes" / "win_models_prompt_logger.py"
    ensure_dir(target.parent)
    target.write_text(PROMPT_LOGGER_SOURCE.read_text(encoding="utf-8"), encoding="utf-8", newline="\n")
    return target


def env_truthy(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def pip_install(python: Path, packages: list[str], extra_args: list[str] | None = None) -> None:
    command: list[str | os.PathLike[str]] = [
        "uv",
        "pip",
        "install",
        "--python",
        python,
        "--link-mode",
        "copy",
        "--upgrade",
    ]
    command.extend(packages)
    if extra_args:
        command.extend(extra_args)
    run(command)


def install_dependencies(args: argparse.Namespace, python: Path, comfy_home: Path) -> None:
    if args.torch != "skip":
        if args.torch == "nvidia":
            pip_install(
                python,
                ["torch", "torchvision", "torchaudio"],
                ["--extra-index-url", args.torch_index_url],
            )
        elif args.torch == "cpu":
            pip_install(python, ["torch", "torchvision", "torchaudio"])
        else:
            raise ValueError(f"Unsupported torch install mode: {args.torch}")

    requirements = comfy_home / "requirements.txt"
    if not requirements.exists():
        raise FileNotFoundError(f"Missing {requirements}")
    run(
        [
            "uv",
            "pip",
            "install",
            "--python",
            python,
            "--link-mode",
            "copy",
            "--upgrade",
            "-r",
            requirements,
        ]
    )


def setup(args: argparse.Namespace) -> None:
    comfy_home = Path(args.comfy_home)
    model_root = Path(args.model_root)
    echo("=== ComfyUI setup ===")
    echo(f"ComfyHome={comfy_home}  ModelRoot={model_root}")

    ensure_comfy_repo(comfy_home, update=args.update)
    if not (comfy_home / ".venv").exists() or args.recreate_venv:
        if args.recreate_venv and (comfy_home / ".venv").exists():
            raise RuntimeError(
                "Refusing to delete an existing venv automatically. "
                "Remove it manually, then re-run setup."
            )
        run(["uv", "venv", "--python", args.python, comfy_home / ".venv"])

    python = venv_python(comfy_home)
    install_dependencies(args, python, comfy_home)
    write_extra_model_paths(comfy_home, model_root)
    prompt_logger = install_prompt_logger_node(comfy_home)
    echo(f"Installed prompt logger custom node: {prompt_logger}")
    ensure_runtime_dirs(args)
    echo("\nDone. Launch with: just comfy serve")


def update(args: argparse.Namespace) -> None:
    comfy_home = Path(args.comfy_home)
    python = venv_python(comfy_home)
    ensure_comfy_repo(comfy_home, update=True)
    install_dependencies(args, python, comfy_home)
    write_extra_model_paths(comfy_home, Path(args.model_root))
    prompt_logger = install_prompt_logger_node(comfy_home)
    echo(f"Installed prompt logger custom node: {prompt_logger}")


def ensure_runtime_dirs(args: argparse.Namespace) -> tuple[Path, Path, Path, Path]:
    comfy_home = Path(args.comfy_home)
    user_dir = Path(args.user_dir) if args.user_dir else comfy_home / "user"
    input_dir = Path(args.input_dir) if args.input_dir else comfy_home / "input"
    output_dir = Path(args.output_dir) if args.output_dir else comfy_home / "output"
    temp_dir = Path(args.temp_dir) if args.temp_dir else comfy_home / "temp"
    for path in (user_dir, input_dir, output_dir, temp_dir):
        ensure_dir(path)
    return user_dir, input_dir, output_dir, temp_dir


def port_owners(port: int) -> set[int]:
    command = (
        f"Get-NetTCPConnection -LocalPort {port} -State Listen -ErrorAction SilentlyContinue "
        "| ForEach-Object { $_.OwningProcess }"
    )
    pids: set[int] = set()
    for line in powershell(command, check=False).splitlines():
        value = line.strip()
        if value.isdigit():
            pids.add(int(value))
    return pids


def tailscale_ipv4() -> str:
    try:
        value = output(["tailscale", "ip", "-4"]).strip().splitlines()[0].strip()
        if value:
            return value
    except Exception:
        pass

    ps = (
        "Get-NetIPAddress -AddressFamily IPv4 "
        "| Where-Object { $_.InterfaceAlias -like '*Tailscale*' -or $_.IPAddress -like '100.*' } "
        "| Select-Object -First 1 -ExpandProperty IPAddress"
    )
    value = powershell(ps, check=False).strip().splitlines()
    if value and value[0].strip():
        return value[0].strip()
    raise RuntimeError("Could not determine Tailscale IPv4 address")


def serve(args: argparse.Namespace) -> None:
    comfy_home = Path(args.comfy_home)
    python = venv_python(comfy_home)
    extra_model_paths = write_extra_model_paths(comfy_home, Path(args.model_root))
    install_prompt_logger_node(comfy_home)
    user_dir, input_dir, output_dir, temp_dir = ensure_runtime_dirs(args)

    if port_owners(args.port):
        echo(f"A server is already listening on port {args.port}.")
        if args.open:
            open_url(f"http://localhost:{args.port}")
        return

    command: list[str | os.PathLike[str]] = [
        python,
        comfy_home / "main.py",
        "--listen",
        args.host,
        "--port",
        str(args.port),
        "--extra-model-paths-config",
        extra_model_paths,
        "--user-directory",
        user_dir,
        "--input-directory",
        input_dir,
        "--output-directory",
        output_dir,
        "--temp-directory",
        temp_dir,
    ]
    if args.lowvram:
        command.append("--lowvram")
    if args.cpu:
        command.append("--cpu")
    if args.open:
        command.append("--auto-launch")
    else:
        command.append("--disable-auto-launch")

    env = os.environ.copy()
    env["COMFYUI_LOG_PROMPTS"] = "1" if args.log_prompts else "0"
    if args.prompt_log_file:
        prompt_log_file = Path(args.prompt_log_file)
    else:
        prompt_log_file = REPO_ROOT / "logs" / "comfyui.prompts.jsonl"
    ensure_dir(prompt_log_file.parent)
    env["COMFYUI_PROMPT_LOG_FILE"] = str(prompt_log_file)

    echo(f"Starting ComfyUI on http://{args.host}:{args.port}")
    if args.log_prompts:
        echo(f"Prompt JSONL log: {prompt_log_file}")
    echo("Server output will stream in this terminal. Press Ctrl+C to stop.")
    if args.host == "0.0.0.0":
        echo(f"Open locally at http://localhost:{args.port}")
    run(command, cwd=comfy_home, env=env)


def stop(args: argparse.Namespace) -> None:
    pids = port_owners(args.port)
    if not pids:
        echo(f"No ComfyUI server found on port {args.port}.")
        return

    for pid in sorted(pids):
        subprocess.run(
            ["taskkill.exe", "/PID", str(pid), "/T"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    still_running = port_owners(args.port)
    if still_running:
        echo("Forcing shutdown...")
        for pid in sorted(still_running):
            subprocess.run(
                ["taskkill.exe", "/F", "/PID", str(pid), "/T"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
    echo(f"Stopped ComfyUI (port {args.port}).")


def status(args: argparse.Namespace) -> None:
    comfy_home = Path(args.comfy_home)
    echo(f"ComfyUI home: {comfy_home}")
    echo(f"Repo present: {(comfy_home / '.git').exists()}")
    echo(f"Venv present: {(comfy_home / '.venv' / 'Scripts' / 'python.exe').exists()}")
    echo(f"Model root: {Path(args.model_root)}")
    echo("\nPorts")
    print(
        powershell(
            f"Get-NetTCPConnection -LocalPort {args.port} -ErrorAction SilentlyContinue "
            "| Select-Object LocalAddress,LocalPort,State,OwningProcess | Format-Table -AutoSize",
            check=False,
        ).rstrip()
    )


def add_common_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--comfy-home", default=str(DEFAULT_COMFYUI_HOME))
    parser.add_argument("--model-root", default=str(DEFAULT_COMFYUI_MODEL_ROOT))


def add_runtime_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--user-dir", default="")
    parser.add_argument("--input-dir", default="")
    parser.add_argument("--output-dir", default="")
    parser.add_argument("--temp-dir", default="")
    parser.add_argument("--log-prompts", action=argparse.BooleanOptionalAction, default=env_truthy("COMFYUI_LOG_PROMPTS", True))
    parser.add_argument("--prompt-log-file", default=os.environ.get("COMFYUI_PROMPT_LOG_FILE", ""))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="win-models comfy")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("setup")
    add_common_args(p)
    add_runtime_args(p)
    p.add_argument("--python", default=os.environ.get("COMFYUI_PYTHON", "3.13"))
    p.add_argument("--torch", choices=("nvidia", "cpu", "skip"), default=os.environ.get("COMFYUI_TORCH", "nvidia"))
    p.add_argument("--torch-index-url", default=DEFAULT_TORCH_INDEX)
    p.add_argument("--update", action="store_true")
    p.add_argument("--recreate-venv", action="store_true")
    p.set_defaults(func=setup)

    p = sub.add_parser("update")
    add_common_args(p)
    p.add_argument("--torch", choices=("nvidia", "cpu", "skip"), default=os.environ.get("COMFYUI_TORCH", "nvidia"))
    p.add_argument("--torch-index-url", default=DEFAULT_TORCH_INDEX)
    p.set_defaults(func=update)

    p = sub.add_parser("serve")
    add_common_args(p)
    add_runtime_args(p)
    p.add_argument("--host", default=os.environ.get("COMFYUI_HOST", "127.0.0.1"))
    p.add_argument("--port", type=int, default=DEFAULT_COMFYUI_PORT)
    p.add_argument("--open", action="store_true")
    p.add_argument("--lan", action="store_true")
    p.add_argument("--lowvram", action="store_true")
    p.add_argument("--cpu", action="store_true")
    p.set_defaults(func=serve)

    p = sub.add_parser("serve-lan")
    add_common_args(p)
    add_runtime_args(p)
    p.add_argument("--port", type=int, default=DEFAULT_COMFYUI_PORT)
    p.add_argument("--open", action="store_true")
    p.add_argument("--lowvram", action="store_true")
    p.add_argument("--cpu", action="store_true")
    p.set_defaults(func=lambda args: serve(argparse.Namespace(**vars(args), host="0.0.0.0", lan=True)))

    p = sub.add_parser("serve-tailscale")
    add_common_args(p)
    add_runtime_args(p)
    p.add_argument("--port", type=int, default=DEFAULT_COMFYUI_PORT)
    p.add_argument("--open", action="store_true")
    p.add_argument("--lowvram", action="store_true")
    p.add_argument("--cpu", action="store_true")
    p.set_defaults(
        func=lambda args: serve(
            argparse.Namespace(
                **vars(args),
                host=f"127.0.0.1,{tailscale_ipv4()}",
                lan=False,
            )
        )
    )

    p = sub.add_parser("stop")
    p.add_argument("--port", type=int, default=DEFAULT_COMFYUI_PORT)
    p.set_defaults(func=stop)

    p = sub.add_parser("status")
    add_common_args(p)
    p.add_argument("--port", type=int, default=DEFAULT_COMFYUI_PORT)
    p.set_defaults(func=status)
    return parser


def main(argv: list[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    if getattr(args, "lan", False):
        args.host = "0.0.0.0"
    args.func(args)
