from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from .common import echo, ensure_dir, open_url, output, powershell, run
from .config import DEFAULT_COMFYUI_HOME, DEFAULT_COMFYUI_MODEL_ROOT, DEFAULT_COMFYUI_PORT


REPO_URL = "https://github.com/Comfy-Org/ComfyUI.git"
REPO_ROOT = Path(__file__).resolve().parents[2]
PROMPT_LOGGER_SOURCE = (
    REPO_ROOT / "src" / "comfyui" / "custom_nodes" / "win_models_prompt_logger.py"
)
WORKFLOW_TEMPLATES_SOURCE = (
    REPO_ROOT / "src" / "comfyui" / "custom_nodes" / "win_models_templates"
)
DEFAULT_TORCH_INDEX = os.environ.get(
    "COMFYUI_TORCH_INDEX_URL", "https://download.pytorch.org/whl/cu130"
)
MODEL_SUBDIRS = (
    "checkpoints",
    "clip",
    "clip_vision",
    "configs",
    "controlnet",
    "diffusion_models",
    "embeddings",
    "loras",
    "style_models",
    "text_encoders",
    "unet",
    "upscale_models",
    "vae",
)
SILLYTAVERN_WORKFLOW_DIR = REPO_ROOT / "outputs"


def venv_python(comfy_home: Path) -> Path:
    python = comfy_home / ".venv" / "Scripts" / "python.exe"
    if not python.exists():
        raise FileNotFoundError(
            f"Missing ComfyUI venv at {python}. Run: just comfy setup"
        )
    return python


def ensure_comfy_repo(comfy_home: Path, *, update: bool = False) -> None:
    if (comfy_home / ".git").exists():
        if update:
            run(["git", "-C", comfy_home, "pull", "--ff-only"])
        else:
            echo(f"ComfyUI repo already present: {comfy_home}")
        return

    if comfy_home.exists() and any(comfy_home.iterdir()):
        raise FileExistsError(
            f"{comfy_home} exists but is not a git checkout. Move it aside or set COMFYUI_HOME."
        )

    ensure_dir(comfy_home.parent)
    run(["git", "clone", REPO_URL, comfy_home])


def write_extra_model_paths(comfy_home: Path, model_root: Path) -> Path:
    ensure_dir(model_root)
    for subdir in MODEL_SUBDIRS:
        ensure_dir(model_root / subdir)

    config = comfy_home / "extra_model_paths.yaml"
    lines = [
        "# Generated by win-models. Keep shared diffusion assets under COMFYUI_MODEL_ROOT.",
        "win_models:",
        f"    base_path: {model_root}",
        "    is_default: true",
    ]
    for subdir in MODEL_SUBDIRS:
        lines.append(f"    {subdir}: {subdir}")
    config.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    echo(f"Wrote {config}")
    return config


def install_prompt_logger_node(comfy_home: Path) -> Path:
    if not PROMPT_LOGGER_SOURCE.exists():
        raise FileNotFoundError(f"Missing prompt logger source: {PROMPT_LOGGER_SOURCE}")
    target = comfy_home / "custom_nodes" / "win_models_prompt_logger.py"
    ensure_dir(target.parent)
    target.write_text(PROMPT_LOGGER_SOURCE.read_text(encoding="utf-8"), encoding="utf-8", newline="\n")
    return target


def install_workflow_templates_node(comfy_home: Path) -> Path:
    if not WORKFLOW_TEMPLATES_SOURCE.exists():
        raise FileNotFoundError(f"Missing workflow templates source: {WORKFLOW_TEMPLATES_SOURCE}")
    target = comfy_home / "custom_nodes" / "win_models_templates"
    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(WORKFLOW_TEMPLATES_SOURCE, target)
    return target


def tee_process_output(
    args: list[str | os.PathLike[str]],
    *,
    cwd: Path,
    env: dict[str, str],
    stdout_log: Path,
    stderr_log: Path,
) -> None:
    printable = " ".join(str(a) for a in args)
    echo(f"> {printable}")
    ensure_dir(stdout_log.parent)
    ensure_dir(stderr_log.parent)
    header = f"\n\n--- ComfyUI started {time.strftime('%Y-%m-%d %H:%M:%S')} ---\n".encode("utf-8")

    with stdout_log.open("ab", buffering=0) as out_file, stderr_log.open("ab", buffering=0) as err_file:
        out_file.write(header)
        err_file.write(header)
        process = subprocess.Popen(
            [str(a) for a in args],
            cwd=cwd,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        def pump(pipe: Any, log_file: Any) -> None:
            try:
                while True:
                    chunk = pipe.read(4096)
                    if not chunk:
                        break
                    log_file.write(chunk)
            finally:
                pipe.close()

        threads = [
            threading.Thread(target=pump, args=(process.stdout, out_file), daemon=True),
            threading.Thread(target=pump, args=(process.stderr, err_file), daemon=True),
        ]
        for thread in threads:
            thread.start()
        return_code = process.wait()
        for thread in threads:
            thread.join()
    if return_code != 0:
        raise SystemExit(return_code)


def env_truthy(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def pip_install(python: Path, packages: list[str], extra_args: list[str] | None = None) -> None:
    command: list[str | os.PathLike[str]] = [
        "uv",
        "pip",
        "install",
        "--python",
        python,
        "--link-mode",
        "copy",
        "--upgrade",
    ]
    command.extend(packages)
    if extra_args:
        command.extend(extra_args)
    run(command)


def install_dependencies(args: argparse.Namespace, python: Path, comfy_home: Path) -> None:
    if args.torch != "skip":
        if args.torch == "nvidia":
            pip_install(
                python,
                ["torch", "torchvision", "torchaudio"],
                ["--extra-index-url", args.torch_index_url],
            )
        elif args.torch == "cpu":
            pip_install(python, ["torch", "torchvision", "torchaudio"])
        else:
            raise ValueError(f"Unsupported torch install mode: {args.torch}")

    requirements = comfy_home / "requirements.txt"
    if not requirements.exists():
        raise FileNotFoundError(f"Missing {requirements}")
    run(
        [
            "uv",
            "pip",
            "install",
            "--python",
            python,
            "--link-mode",
            "copy",
            "--upgrade",
            "-r",
            requirements,
        ]
    )


def setup(args: argparse.Namespace) -> None:
    comfy_home = Path(args.comfy_home)
    model_root = Path(args.model_root)
    echo("=== ComfyUI setup ===")
    echo(f"ComfyHome={comfy_home}  ModelRoot={model_root}")

    ensure_comfy_repo(comfy_home, update=args.update)
    if not (comfy_home / ".venv").exists() or args.recreate_venv:
        if args.recreate_venv and (comfy_home / ".venv").exists():
            raise RuntimeError(
                "Refusing to delete an existing venv automatically. "
                "Remove it manually, then re-run setup."
            )
        run(["uv", "venv", "--python", args.python, comfy_home / ".venv"])

    python = venv_python(comfy_home)
    install_dependencies(args, python, comfy_home)
    write_extra_model_paths(comfy_home, model_root)
    prompt_logger = install_prompt_logger_node(comfy_home)
    echo(f"Installed prompt logger custom node: {prompt_logger}")
    templates = install_workflow_templates_node(comfy_home)
    echo(f"Installed workflow templates custom node: {templates}")
    ensure_runtime_dirs(args)
    echo("\nDone. Launch with: just comfy serve")


def update(args: argparse.Namespace) -> None:
    comfy_home = Path(args.comfy_home)
    python = venv_python(comfy_home)
    ensure_comfy_repo(comfy_home, update=True)
    install_dependencies(args, python, comfy_home)
    write_extra_model_paths(comfy_home, Path(args.model_root))
    prompt_logger = install_prompt_logger_node(comfy_home)
    echo(f"Installed prompt logger custom node: {prompt_logger}")
    templates = install_workflow_templates_node(comfy_home)
    echo(f"Installed workflow templates custom node: {templates}")


def ensure_runtime_dirs(args: argparse.Namespace) -> tuple[Path, Path, Path, Path]:
    comfy_home = Path(args.comfy_home)
    user_dir = Path(args.user_dir) if args.user_dir else comfy_home / "user"
    input_dir = Path(args.input_dir) if args.input_dir else comfy_home / "input"
    output_dir = Path(args.output_dir) if args.output_dir else comfy_home / "output"
    temp_dir = Path(args.temp_dir) if args.temp_dir else comfy_home / "temp"
    for path in (user_dir, input_dir, output_dir, temp_dir):
        ensure_dir(path)
    return user_dir, input_dir, output_dir, temp_dir


def port_owners(port: int) -> set[int]:
    command = (
        f"Get-NetTCPConnection -LocalPort {port} -State Listen -ErrorAction SilentlyContinue "
        "| ForEach-Object { $_.OwningProcess }"
    )
    pids: set[int] = set()
    for line in powershell(command, check=False).splitlines():
        value = line.strip()
        if value.isdigit():
            pids.add(int(value))
    return pids


def tailscale_ipv4() -> str:
    try:
        value = output(["tailscale", "ip", "-4"]).strip().splitlines()[0].strip()
        if value:
            return value
    except Exception:
        pass

    ps = (
        "Get-NetIPAddress -AddressFamily IPv4 "
        "| Where-Object { $_.InterfaceAlias -like '*Tailscale*' -or $_.IPAddress -like '100.*' } "
        "| Select-Object -First 1 -ExpandProperty IPAddress"
    )
    value = powershell(ps, check=False).strip().splitlines()
    if value and value[0].strip():
        return value[0].strip()
    raise RuntimeError("Could not determine Tailscale IPv4 address")


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: Any) -> None:
    ensure_dir(path.parent)
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def sort_node_ids(node_ids: Any) -> list[str]:
    def key(value: Any) -> tuple[int, Any]:
        text = str(value)
        if text.isdigit():
            return (0, int(text))
        return (1, text)

    return sorted((str(node_id) for node_id in node_ids), key=key)


def compact_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def format_prompt_log_line(line: str) -> list[str]:
    try:
        record = json.loads(line)
    except json.JSONDecodeError:
        return [line.rstrip()]

    payload = record.get("payload", {}) if isinstance(record, dict) else {}
    prompt = payload.get("prompt") if isinstance(payload, dict) else None
    if not isinstance(prompt, dict):
        return [compact_json(record)]

    header = {
        "time": record.get("time"),
        "client_id": payload.get("client_id"),
        "nodes": len(prompt),
    }
    lines = [compact_json(header)]
    for node_id in sort_node_ids(prompt.keys()):
        node = prompt[node_id]
        if not isinstance(node, dict):
            lines.append(compact_json({"id": node_id, "value": node}))
            continue
        line_payload = {
            "id": node_id,
            "class_type": node.get("class_type"),
            "title": (node.get("_meta") or {}).get("title"),
            "inputs": node.get("inputs", {}),
        }
        lines.append(compact_json(line_payload))
    return lines


def tail_lines(path: Path, lines: int) -> list[str]:
    if lines <= 0:
        return []
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", errors="replace") as handle:
        return handle.readlines()[-lines:]


def follow_file(path: Path, start_at_end: bool) -> Any:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a+", encoding="utf-8", errors="replace") as handle:
        if start_at_end:
            handle.seek(0, os.SEEK_END)
        else:
            handle.seek(0)
        while True:
            line = handle.readline()
            if line:
                yield line
            else:
                time.sleep(0.5)


def prompt_logs(args: argparse.Namespace) -> None:
    path = Path(args.file)
    echo(f"Tailing ComfyUI prompt log: {path}")
    for line in tail_lines(path, args.lines):
        for formatted in format_prompt_log_line(line):
            print(formatted)
        print()
    if not args.follow:
        return
    for line in follow_file(path, start_at_end=True):
        for formatted in format_prompt_log_line(line):
            print(formatted)
        print()


def fetch_object_info(comfy_url: str) -> dict[str, Any]:
    url = comfy_url.rstrip("/") + "/object_info"
    with urllib.request.urlopen(url, timeout=15) as response:
        return json.loads(response.read().decode("utf-8"))


def is_api_workflow(payload: Any) -> bool:
    if not isinstance(payload, dict) or not payload:
        return False
    return all(
        isinstance(value, dict) and "class_type" in value and "inputs" in value
        for value in payload.values()
    )


def is_ui_workflow(payload: Any) -> bool:
    return isinstance(payload, dict) and isinstance(payload.get("nodes"), list)


def input_type(spec: Any) -> str | None:
    if isinstance(spec, list) and spec:
        value = spec[0]
        if isinstance(value, str):
            return value
    return None


def widget_input_names(node_info: dict[str, Any]) -> list[str]:
    inputs = node_info.get("input", {})
    input_order = node_info.get("input_order", {})
    names: list[str] = []
    for group in ("required", "optional"):
        ordered = input_order.get(group) or list((inputs.get(group) or {}).keys())
        for name in ordered:
            spec = (inputs.get(group) or {}).get(name)
            kind = input_type(spec)
            if kind in {"MODEL", "CLIP", "VAE", "CONDITIONING", "LATENT", "IMAGE", "MASK"}:
                continue
            names.append(name)
    return names


def api_links_from_ui_workflow(payload: dict[str, Any]) -> dict[tuple[int, str], list[Any]]:
    nodes = {int(node["id"]): node for node in payload.get("nodes", []) if "id" in node}
    api_links: dict[tuple[int, str], list[Any]] = {}
    for link in payload.get("links", []):
        if not isinstance(link, list) or len(link) < 5:
            continue
        _link_id, origin_id, origin_slot, target_id, target_slot = link[:5]
        target = nodes.get(int(target_id))
        if not target:
            continue
        inputs = target.get("inputs") or []
        if int(target_slot) >= len(inputs):
            continue
        input_name = inputs[int(target_slot)].get("name")
        if input_name:
            api_links[(int(target_id), str(input_name))] = [str(origin_id), int(origin_slot)]
    return api_links


def ui_workflow_to_api(payload: dict[str, Any], object_info: dict[str, Any]) -> dict[str, Any]:
    api_links = api_links_from_ui_workflow(payload)
    result: dict[str, Any] = {}
    for node in payload.get("nodes", []):
        node_id = int(node.get("id"))
        class_type = node.get("type")
        if not class_type or class_type not in object_info:
            continue
        if node.get("mode") == 2:
            continue

        node_info = object_info[class_type]
        inputs: dict[str, Any] = {}
        for input_node in node.get("inputs") or []:
            input_name = input_node.get("name")
            if input_name and (node_id, input_name) in api_links:
                inputs[input_name] = api_links[(node_id, input_name)]

        widget_values = list(node.get("widgets_values") or [])
        widget_index = 0
        input_specs = node_info.get("input", {})
        for input_name in widget_input_names(node_info):
            if input_name in inputs or widget_index >= len(widget_values):
                continue
            inputs[input_name] = widget_values[widget_index]
            widget_index += 1
            spec = (input_specs.get("required") or {}).get(input_name)
            spec = spec or (input_specs.get("optional") or {}).get(input_name)
            if (
                isinstance(spec, list)
                and len(spec) > 1
                and isinstance(spec[1], dict)
                and spec[1].get("control_after_generate")
                and widget_index < len(widget_values)
            ):
                widget_index += 1

        result[str(node_id)] = {
            "class_type": class_type,
            "_meta": {"title": node.get("title") or class_type},
            "inputs": inputs,
        }
    return result


def parse_path_value(value: str) -> tuple[str, str, str]:
    if "=" not in value:
        raise ValueError(f"Expected NODE.INPUT=VALUE, got: {value}")
    path, replacement = value.split("=", 1)
    if "." not in path:
        raise ValueError(f"Expected NODE.INPUT=VALUE, got: {value}")
    node_id, input_name = path.split(".", 1)
    return node_id, input_name, replacement


def template_token(name: str, *, quoted: bool = False) -> str:
    if name.startswith("%") and name.endswith("%"):
        token = name
    else:
        token = f"%{name}%"
    if quoted:
        return f'"{token}"'
    return token


def coerce_value(value: str) -> Any:
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        return value


def text_with_appended_placeholder(value: Any, name: str) -> str:
    text = "" if value is None else str(value).strip()
    token = template_token(name, quoted=True)
    if not text:
        return token
    if token in text:
        return text
    separator = "" if text.endswith((",", " ")) else ", "
    return f"{text}{separator}{token}"


def text_with_prepended_placeholder(value: Any, name: str) -> str:
    text = "" if value is None else str(value).strip()
    token = template_token(name, quoted=True)
    if not text:
        return token
    if token in text:
        return text
    return f"{token}, {text}"


def text_with_placeholder_before(value: Any, name_and_marker: str) -> str:
    if "::" not in name_and_marker:
        raise ValueError(
            "Expected NODE.INPUT=NAME::MARKER for --insert-placeholder-before"
        )
    name, marker = name_and_marker.split("::", 1)
    text = "" if value is None else str(value).strip()
    token = template_token(name, quoted=True)
    if not text:
        return token
    if token in text:
        return text
    if marker and marker in text:
        return text.replace(marker, f"{token}, {marker}", 1)
    return text_with_appended_placeholder(text, name)


def apply_workflow_overrides(
    workflow: dict[str, Any],
    *,
    set_values: list[str],
    placeholders: list[str],
    append_placeholders: list[str],
    prepend_placeholders: list[str],
    insert_placeholders_before: list[str],
) -> None:
    for item in set_values:
        node_id, input_name, replacement = parse_path_value(item)
        node = workflow.get(node_id)
        if not node:
            raise KeyError(f"Workflow has no node {node_id}")
        node.setdefault("inputs", {})[input_name] = coerce_value(replacement)

    for item in placeholders:
        node_id, input_name, name = parse_path_value(item)
        node = workflow.get(node_id)
        if not node:
            raise KeyError(f"Workflow has no node {node_id}")
        node.setdefault("inputs", {})[input_name] = template_token(name)

    for item in append_placeholders:
        node_id, input_name, name = parse_path_value(item)
        node = workflow.get(node_id)
        if not node:
            raise KeyError(f"Workflow has no node {node_id}")
        inputs = node.setdefault("inputs", {})
        inputs[input_name] = text_with_appended_placeholder(inputs.get(input_name), name)

    for item in prepend_placeholders:
        node_id, input_name, name = parse_path_value(item)
        node = workflow.get(node_id)
        if not node:
            raise KeyError(f"Workflow has no node {node_id}")
        inputs = node.setdefault("inputs", {})
        inputs[input_name] = text_with_prepended_placeholder(inputs.get(input_name), name)

    for item in insert_placeholders_before:
        node_id, input_name, name_and_marker = parse_path_value(item)
        node = workflow.get(node_id)
        if not node:
            raise KeyError(f"Workflow has no node {node_id}")
        inputs = node.setdefault("inputs", {})
        inputs[input_name] = text_with_placeholder_before(
            inputs.get(input_name),
            name_and_marker,
        )


def st_workflow(args: argparse.Namespace) -> None:
    source = Path(args.workflow)
    payload = load_json(source)
    if is_api_workflow(payload):
        workflow = payload
    elif is_ui_workflow(payload):
        try:
            object_info = fetch_object_info(args.comfy_url)
        except (OSError, urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
            raise RuntimeError(
                "UI-format workflows need a running ComfyUI server so node widget "
                f"metadata can be read from {args.comfy_url}/object_info: {exc}"
            ) from exc
        workflow = ui_workflow_to_api(payload, object_info)
    else:
        raise ValueError(f"{source} is neither ComfyUI UI workflow JSON nor API workflow JSON")

    apply_workflow_overrides(
        workflow,
        set_values=args.set,
        placeholders=args.placeholder,
        append_placeholders=args.append_placeholder,
        prepend_placeholders=args.prepend_placeholder,
        insert_placeholders_before=args.insert_placeholder_before,
    )

    name = args.name or f"{source.stem}_sillytavern_api"
    output_dir = Path(args.output_dir)
    output = output_dir / (name if name.lower().endswith(".json") else f"{name}.json")
    write_json(output, workflow)
    echo(f"Wrote SillyTavern ComfyUI API workflow: {output}")


def serve(args: argparse.Namespace) -> None:
    comfy_home = Path(args.comfy_home)
    python = venv_python(comfy_home)
    extra_model_paths = write_extra_model_paths(comfy_home, Path(args.model_root))
    install_prompt_logger_node(comfy_home)
    install_workflow_templates_node(comfy_home)
    user_dir, input_dir, output_dir, temp_dir = ensure_runtime_dirs(args)

    if port_owners(args.port):
        echo(f"A server is already listening on port {args.port}.")
        if args.open:
            open_url(f"http://localhost:{args.port}")
        return

    command: list[str | os.PathLike[str]] = [
        python,
        comfy_home / "main.py",
        "--listen",
        args.host,
        "--port",
        str(args.port),
        "--extra-model-paths-config",
        extra_model_paths,
        "--user-directory",
        user_dir,
        "--input-directory",
        input_dir,
        "--output-directory",
        output_dir,
        "--temp-directory",
        temp_dir,
    ]
    memory_mode = args.memory_mode
    if args.lowvram:
        memory_mode = "lowvram"
    if args.cpu:
        memory_mode = "cpu"
    if memory_mode != "auto":
        command.append(f"--{memory_mode}")
    if args.assets:
        command.append("--enable-assets")
    if args.open:
        command.append("--auto-launch")
    else:
        command.append("--disable-auto-launch")

    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    env["PYTHONUTF8"] = "1"
    env["COMFYUI_LOG_PROMPTS"] = "1" if args.log_prompts else "0"
    if args.prompt_log_file:
        prompt_log_file = Path(args.prompt_log_file)
    else:
        prompt_log_file = REPO_ROOT / "logs" / "comfyui.prompts.jsonl"
    ensure_dir(prompt_log_file.parent)
    env["COMFYUI_PROMPT_LOG_FILE"] = str(prompt_log_file)
    log_dir = Path(args.log_dir) if args.log_dir else REPO_ROOT / "logs"
    stdout_log = log_dir / "comfyui.out.log"
    stderr_log = log_dir / "comfyui.err.log"

    echo(f"Starting ComfyUI on http://{args.host}:{args.port}")
    if args.log_prompts:
        echo(f"Prompt JSONL log: {prompt_log_file}")
    echo(f"Server stdout log: {stdout_log}")
    echo(f"Server stderr log: {stderr_log}")
    echo("Server output will tee to logs only. Use `just comfy logs` to follow logs.")
    tee_process_output(command, cwd=comfy_home, env=env, stdout_log=stdout_log, stderr_log=stderr_log)


def stop(args: argparse.Namespace) -> None:
    pids = port_owners(args.port)
    if not pids:
        echo(f"No ComfyUI server found on port {args.port}.")
        return

    for pid in sorted(pids):
        subprocess.run(
            ["taskkill.exe", "/PID", str(pid), "/T"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    still_running = port_owners(args.port)
    if still_running:
        echo("Forcing shutdown...")
        for pid in sorted(still_running):
            subprocess.run(
                ["taskkill.exe", "/F", "/PID", str(pid), "/T"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
    echo(f"Stopped ComfyUI (port {args.port}).")


def status(args: argparse.Namespace) -> None:
    comfy_home = Path(args.comfy_home)
    echo(f"ComfyUI home: {comfy_home}")
    echo(f"Repo present: {(comfy_home / '.git').exists()}")
    echo(f"Venv present: {(comfy_home / '.venv' / 'Scripts' / 'python.exe').exists()}")
    echo(f"Model root: {Path(args.model_root)}")
    echo("\nPorts")
    print(
        powershell(
            f"Get-NetTCPConnection -LocalPort {args.port} -ErrorAction SilentlyContinue "
            "| Select-Object LocalAddress,LocalPort,State,OwningProcess | Format-Table -AutoSize",
            check=False,
        ).rstrip()
    )


def add_common_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--comfy-home", default=str(DEFAULT_COMFYUI_HOME))
    parser.add_argument("--model-root", default=str(DEFAULT_COMFYUI_MODEL_ROOT))


def add_runtime_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--user-dir", default="")
    parser.add_argument("--input-dir", default="")
    parser.add_argument("--output-dir", default="")
    parser.add_argument("--temp-dir", default="")
    parser.add_argument("--log-dir", default=os.environ.get("COMFYUI_LOG_DIR", ""))
    parser.add_argument("--log-prompts", action=argparse.BooleanOptionalAction, default=env_truthy("COMFYUI_LOG_PROMPTS", True))
    parser.add_argument("--prompt-log-file", default=os.environ.get("COMFYUI_PROMPT_LOG_FILE", ""))
    parser.add_argument("--assets", action=argparse.BooleanOptionalAction, default=env_truthy("COMFYUI_ASSETS", True))


def add_memory_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--memory-mode",
        choices=("auto", "highvram", "gpu-only", "lowvram", "novram", "cpu"),
        default=os.environ.get("COMFYUI_MEMORY_MODE", "auto"),
        help="ComfyUI model memory policy. Use highvram to keep models in GPU memory when possible.",
    )
    parser.add_argument("--lowvram", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument("--cpu", action="store_true", help=argparse.SUPPRESS)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="win-models comfy")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("setup")
    add_common_args(p)
    add_runtime_args(p)
    p.add_argument("--python", default=os.environ.get("COMFYUI_PYTHON", "3.13"))
    p.add_argument("--torch", choices=("nvidia", "cpu", "skip"), default=os.environ.get("COMFYUI_TORCH", "nvidia"))
    p.add_argument("--torch-index-url", default=DEFAULT_TORCH_INDEX)
    p.add_argument("--update", action="store_true")
    p.add_argument("--recreate-venv", action="store_true")
    p.set_defaults(func=setup)

    p = sub.add_parser("update")
    add_common_args(p)
    p.add_argument("--torch", choices=("nvidia", "cpu", "skip"), default=os.environ.get("COMFYUI_TORCH", "nvidia"))
    p.add_argument("--torch-index-url", default=DEFAULT_TORCH_INDEX)
    p.set_defaults(func=update)

    p = sub.add_parser("st-workflow")
    p.add_argument("workflow", help="ComfyUI UI-format or API-format workflow JSON")
    p.add_argument("--name", default="", help="Output filename or stem. Defaults to <input>_sillytavern_api.json")
    p.add_argument("--output-dir", default=str(SILLYTAVERN_WORKFLOW_DIR))
    p.add_argument("--comfy-url", default=os.environ.get("COMFYUI_URL", f"http://127.0.0.1:{DEFAULT_COMFYUI_PORT}"))
    p.add_argument(
        "--set",
        action="append",
        default=[],
        metavar="NODE.INPUT=VALUE",
        help="Set an API node input. VALUE is JSON-decoded when possible, otherwise kept as text.",
    )
    p.add_argument(
        "--placeholder",
        action="append",
        default=[],
        metavar="NODE.INPUT=NAME",
        help="Set an API node input to a SillyTavern placeholder, e.g. 6.text=prompt -> %%prompt%%.",
    )
    p.add_argument(
        "--append-placeholder",
        action="append",
        default=[],
        metavar="NODE.INPUT=NAME",
        help="Append a SillyTavern placeholder to an existing text input.",
    )
    p.add_argument(
        "--prepend-placeholder",
        action="append",
        default=[],
        metavar="NODE.INPUT=NAME",
        help="Prepend a SillyTavern placeholder to an existing text input.",
    )
    p.add_argument(
        "--insert-placeholder-before",
        action="append",
        default=[],
        metavar="NODE.INPUT=NAME::MARKER",
        help="Insert a placeholder before MARKER inside an existing text input.",
    )
    p.set_defaults(func=st_workflow)

    p = sub.add_parser("prompt-logs")
    p.add_argument("--file", default=str(REPO_ROOT / "logs" / "comfyui.prompts.jsonl"))
    p.add_argument("--lines", type=int, default=20)
    p.add_argument("--follow", action=argparse.BooleanOptionalAction, default=True)
    p.set_defaults(func=prompt_logs)

    p = sub.add_parser("serve")
    add_common_args(p)
    add_runtime_args(p)
    p.add_argument("--host", default=os.environ.get("COMFYUI_HOST", "127.0.0.1"))
    p.add_argument("--port", type=int, default=DEFAULT_COMFYUI_PORT)
    p.add_argument("--open", action="store_true")
    add_memory_args(p)
    p.set_defaults(func=serve)

    p = sub.add_parser("serve-tailscale")
    add_common_args(p)
    add_runtime_args(p)
    p.add_argument("--port", type=int, default=DEFAULT_COMFYUI_PORT)
    p.add_argument("--open", action="store_true")
    add_memory_args(p)
    p.set_defaults(
        func=lambda args: serve(
            argparse.Namespace(
                **vars(args),
                host=tailscale_ipv4(),
            )
        )
    )

    p = sub.add_parser("stop")
    p.add_argument("--port", type=int, default=DEFAULT_COMFYUI_PORT)
    p.set_defaults(func=stop)

    p = sub.add_parser("status")
    add_common_args(p)
    p.add_argument("--port", type=int, default=DEFAULT_COMFYUI_PORT)
    p.set_defaults(func=status)
    return parser


def main(argv: list[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)
